apiVersion: v1
kind: Secret
metadata:
  name: swarm-secrets
  labels:
    {{- include "swarm-worker.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.env.DEEPSEEK_API_KEY }}
  DEEPSEEK_API_KEY: {{ .Values.env.DEEPSEEK_API_KEY | b64enc }}
  {{- end }}
  {{- if .Values.env.GROQ_API_KEY }}
  GROQ_API_KEY: {{ .Values.env.GROQ_API_KEY | b64enc }}
  {{- end }}
